---
# template taken from https://github.com/gael-close/ieeetran
#----------------------------------------------------------
title: Arrival Management with Open Data
format:
  ieeetran-pdf:
    keep-tex: true
    
author:
  - name: Rainer Koelle
    orcid: 0000-0000-0000-0000
    email: rainer.koelle@eurocontrol.int
    note: 1  # workaround i/o linked affiliation
  - name: Second Author
    orcid: 0000-0000-0000-0000
    email: second@example.org
    note: 1
  - name: Third Author
    email: third@example.org
    note: 2
#date: 01-Jan-2022.
affiliations:
  - id: 1
    name: Performance Review Unit, EUROCONTROL
    city: Brussels
    country: Belgium
  - id: 2
    name: Some corporation
    city: New York
    country: USA

abstract: |
  This document is a sample illustrating the Quarto `ieeetran` template.
  It includes the key elements of a scientific articles 
  (references, equations, figures, tables, code, cross references).
  The template enables the generation of IEEE-formatted article from a Jupypter notebook.
keywords: [template, demo]
reference-section-title: References
bibliography: bibliography.bib
note: Extra footnote.
# filters:
#    - latex-environment
environments: [mytable, mywidetable]
---

# Introduction

Operational efficiency is a key element of addressing aviation's contribution to climate change.
<!-- verbatim copy --> Emissions may increase due to the expected growth in international air traffic until lower emitting technologies and fuels and other mitigating measures are developed and deployed ..
<!-- end copy --> ICAO adopted at its 41st Assembly a long-term aspirational goal for international aviation [@icao2022].
In support to the Paris Agreement, the goal is to achieve net-zero carbon emissions by 2050.

Levers for fuel reduction:

\* operational efficiency

\* market-based measures

\* sustainable aviation fuel

\* new aircraft propulsion and airframes

A wider use and pick-up of sustainable aviation fuel, and new aircraft propulsion technologies or aircraft design requires further research.

Despite the introduction of an initial market-based mechanism, immediate action to curb fuel burn and CO2 emissions rests with improvements of operational efficiency.

The contribution of this paper comprise:

-   conceptualisation of sequencing separation for arrival management and development of an open data and open software based implementation of the approach; and

-   use-case application of the developed approach on a subset of airports within the European <!-- and international context -->

# Trajectory-Based Operations - Arrival Management

## header 2

# Data and Conceptual Approach

## Approach

data preparation

-   trajectory data - Opensky Network, weekly downloads
-   airport information - Openstreet Map

data downloaded & script development, data cleaning

### Trajectory Flight Phase Segmentation & Milestone

Different approaches exists to detect and describe aircraft flight phases, e.g. recent machine learning algorithm [@sun2017flightphase].
This paper implements a heuristic approach with a focus on the detection of arrival traffic at the study airports.

### Landing Runway Identification

The identification of the landing direction is based on a simple geospatial heuristic.
Conceptually, aircraft are aligned with the runway (centerline) before landing.
An aircraft is assigned to a landing runway based on the closeness of its pre-landing positions to the extended runway centerline.

## Arrival Sequencing

Spacing deviation

Let us consider a pair of consecutive landing aircraft denoted leader and trailer, with s their required time spacing1.
Using the constant time delay principle, the spacing deviation (or spacing error) at time t considers the current position of trailer at time t, and the past position of leader at time t -- s.
Precisely, it is defined as the difference between the respective minimum times from these two positions (see figure below): spacing deviation (t) = min time (trailer (t)) -- min time (leader (t -- s))

# Case Study - Results

## Data Sampling

At the time of writing no global open flight table exists.
For this study, we validated the sample with reference data available to the Performance Review Unit.
Under the EUROCONTROL Performance Review System, airport operators report movement data on a monthly basis [@apdf_v1_2019].

# Conclusions

<!-- what did this paper show -->

This paper aimed at exploring a data-driven approach to measuring arrival management based on open data.

<!-- strength and weaknesses -->

<!-- application -->

<!-- further research -->

<!-- final appraisal -->

# Reproducibility {.unnumbered}

This paper has been built with the R/RStudio ecosystem.
The draft manuscript and its supporting data preparatory steps are archived at https://github.com/rainer-rq-koelle/paper-2023-ICNS.

The script to download the weekly global datasets are included.
The cleaned trajectory data is stored at: \<\<tbd\>\>.

# Acknowledgment and Disclaimer {.unnumbered}

The authors thank the comments by XX YY ZZ.

The views expressed are the authors' own and do not represent a policy or position of EUROCONTROL <!-- and co-authors organisations -->.
